//Fetch Posts
export const REQUEST_POSTS_PENDING = 'REQUEST_POSTS_PENDING';
export const REQUEST_POSTS_SUCCESS = 'REQUEST_POSTS_SUCCESS';
export const REQUEST_POSTS_FAILED = 'REQUEST_POSTS_FAILED';

//Filter Posts
export const ProductHoldFilters = {
	SHOW_ALL_HOLD: 'SHOW_ALL_HOLD',
	SHOW_HIGH_HOLD: 'SHOW_HIGH_HOLD',
	SHOW_MED_HOLD: 'SHOW_MED_HOLD',
	SHOW_LOW_HOLD: 'SHOW_LOW_HOLD'	
}
export const ProductShineFilters = {
	SHOW_ALL_SHINE: 'SHOW_ALL_SHINE',
	SHOW_HIGH_SHINE: 'SHOW_HIGH_SHINE',
	SHOW_MED_SHINE: 'SHOW_MED_SHINE',
	SHOW_LOW_SHINE: 'SHOW_LOW_SHINE'
}
export const HairLengthFilters = {
	SHOW_ALL_LENGTH: 'SHOW_ALL_LENGTH',
	SHOW_SHORT_LENGTH: 'SHOW_SHORT_LENGTH',
	SHOW_MED_LENGTH: 'SHOW_MED_LENGTH',
	SHOW_LONG_LENGTH: 'SHOW_LONG_LENGTH'
}
export const HairTypeFilters = {
	SHOW_ALL_HAIRTYPES : 'SHOW_ALL_HAIRTYPES',
	SHOW_STRAIGHT_HAIR : 'SHOW_STARIGHT_HAIR',
	SHOW_WAVY_HAIR : 'SHOW_WAVY_HAIR',
	SHOW_CURLY_HAIR : 'SHOW_CURLY_HAIR',
	SHOW_COILY_HAIR : 'SHOW_COILY_HAIR'
}

export const RESET_FILTER = 'RESET_FILTER';